# Generated by Django 5.0.2 on 2025-05-08 13:33

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_typecustompermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecustompermission',
            name='code_name',
        ),
        migrations.AddField(
            model_name='typecustompermission',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', editable=False, length=6, max_length=9, prefix='pb-', unique=True),
        ),
    ]
