# Generated by Django 5.0.2 on 2025-09-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_typecustompermission_code_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gerant',
        ),
    ]
