# Generated by Django 5.0.2 on 2026-06-21 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_remove_legacy_profile_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=500, verbose_name='Lien')),
                ('type_notif', models.CharField(choices=[('info', 'Information'), ('alert', 'Alerte véhicule'), ('compte', 'Compte'), ('system', 'Système')], default='info', max_length=20, verbose_name='Type')),
                ('categorie', models.CharField(blank=True, choices=[('visite', 'Visite technique'), ('entretien', 'Entretien'), ('assurance', 'Assurance'), ('vignette', 'Vignette'), ('patente', 'Patente'), ('stationnement', 'Stationnement'), ('compte_bloque', 'Compte bloqué'), ('compte_reset', 'Réinitialisation compte'), ('compte_actif', 'Compte activé'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('dedupe_key', models.CharField(blank=True, max_length=120, verbose_name='Clé unique')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='userauths_l_user_id_608294_idx',
            old_name='userauths_l_user_id_6f0a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='userauths_l_ip_addr_47d2ca_idx',
            old_name='userauths_l_ip_addr_0d2f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='userauths_p_user_id_2e40d7_idx',
            old_name='userauths_p_user_id_8b2c1a_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif/Inactif'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'lu', '-created_at'], name='userauths_n_user_id_2e40e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'dedupe_key'], name='userauths_n_user_id_f36e70_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__gt', '')), fields=('user', 'dedupe_key'), name='unique_user_notification_dedupe'),
        ),
    ]
