# Generated by Django 5.0.2 on 2025-01-27 15:25

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='assurances_fil')),
                ('date_saisie', models.DateField()),
                ('date_proch', models.DateField()),
                ('montant', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autrarret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_arret', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
                ('numfich', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billetage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(choices=[(10000, '10000'), (5000, '5000'), (2000, '2000'), (1000, '1000'), (500, '500'), (200, '200'), (100, '100'), (50, '50'), (25, '25'), (10, '10'), (5, '5')])),
                ('nombre', models.IntegerField()),
                ('type', models.CharField(choices=[('Billet', 'Billet'), ('Pièce', 'Pièce')], max_length=10)),
                ('date_saisie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoVehi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcd1234', length=6, max_length=8, prefix='AT', unique=True)),
                ('category', models.CharField(max_length=10, unique=True)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('recette_defaut', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeAdminis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.IntegerField(default=0.0)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('Num_piece', models.CharField(max_length=100)),
                ('Num_fact', models.CharField(max_length=100)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_piece', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_piece', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='entretiens_fil')),
                ('date_Entret', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
                ('date_proch', models.DateField()),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='patentes_fil')),
                ('date_saisie', models.DateField()),
                ('date_proch', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=30, null=True)),
                ('lieu', models.CharField(choices=[('INTERNE', 'INTERNE'), ('EXTERNE', 'EXTERNE')], max_length=20)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PiecEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=30, null=True)),
                ('lieu', models.CharField(choices=[('INTERNE', 'INTERNE'), ('EXTERNE', 'EXTERNE')], max_length=20)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant_previs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chauffeur', models.CharField(max_length=50)),
                ('cpte_comptable', models.CharField(max_length=100)),
                ('numero_fact', models.CharField(max_length=20)),
                ('Num_piece', models.CharField(max_length=100)),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
                ('motif', models.CharField(choices=[('Visite', 'Visite'), ('Panne', 'Panne'), ('Accident', 'Accident')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='reparation_fil')),
                ('num_fich', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('montant', models.IntegerField(default=0)),
                ('prestation', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateField(unique=True)),
                ('montant', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stationnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='carte_station_fil')),
                ('date_saisie', models.DateField()),
                ('date_proch', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(max_length=20)),
                ('duree', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='CARS')),
                ('photo_carte_grise', models.ImageField(upload_to='Photo_Carte_Grise')),
                ('num_cart_grise', models.CharField(max_length=50, unique=True)),
                ('num_Chassis', models.CharField(max_length=50, unique=True)),
                ('date_acquisition', models.DateField()),
                ('cout_acquisition', models.IntegerField(default=0)),
                ('dat_edit_carte_grise', models.DateField()),
                ('date_mis_service', models.DateField()),
                ('date_saisie', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='vignettes_fil')),
                ('date_saisie', models.DateField()),
                ('date_proch', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vis', models.DateTimeField()),
                ('date_sortie', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='visites_fil')),
                ('date_proch', models.DateField()),
                ('montant', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
