# Generated by Django 5.0.2 on 2025-01-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PB_Entreprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_ass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autrarret',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_aut', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billetage',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bielletages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargeadminis',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_chadm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargefixe',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_chf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargevariable',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_var', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decaissement',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_dec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_enc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entretien',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_ent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patente',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_pat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piecechange',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_piechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recette',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_rec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reparation',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_rep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piece',
            name='reparation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='PB_Entreprise.reparation'),
        ),
        migrations.AddField(
            model_name='soldejour',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationnement',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_sta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_veh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catego_vehicule', to='PB_Entreprise.categovehi'),
        ),
        migrations.AddField(
            model_name='stationnement',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_station', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='reparation',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='recette',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='piecechange',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piechang', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='patente',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patantes', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='chargevariable',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargevariables', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='chargefixe',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargefixes', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='autrarret',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autrarrets', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='vignette',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_vig', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vignette',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='PB_Entreprise.vehicule'),
        ),
        migrations.AddField(
            model_name='visitetechnique',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_add_vis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitetechnique',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='PB_Entreprise.vehicule'),
        ),
    ]
