# Generated by Django 5.0.2 on 2025-01-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autrarret',
            name='date',
        ),
    ]
