# Generated by Django 5.0.2 on 2025-08-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0003_remove_autrarret_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CARS'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo_carte_grise',
            field=models.ImageField(blank=True, null=True, upload_to='Photo_Carte_Grise'),
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents_vehicules/')),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='PB_Entreprise.vehicule')),
            ],
            options={
                'ordering': ['-date_saisie'],
            },
        ),
    ]
