# Generated by Django 5.0.2 on 2025-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0006_historicaldocumentvehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreparation',
            name='num_fich',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='num_fich',
            field=models.CharField(max_length=50),
        ),
    ]
