# Generated by Django 5.0.2 on 2025-09-08 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0007_alter_historicalreparation_num_fich_and_more'),
        ('userauths', '0005_delete_gerant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=30)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('tel1', models.CharField(blank=True, max_length=255, null=True)),
                ('tel2', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admingerants', to='userauths.administ')),
                ('gerant_voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerants', to='PB_Entreprise.categovehi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
