# Generated by Django 5.0.2 on 2025-09-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0008_gerant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LignePiecEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=30, null=True)),
                ('lieu', models.CharField(choices=[('INTERNE', 'INTERNE'), ('EXTERNE', 'EXTERNE')], max_length=20)),
                ('montant', models.IntegerField(default=0)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('piecec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='PB_Entreprise.piecechange')),
            ],
        ),
    ]
