# Generated by Django 5.0.2 on 2025-09-11 12:34

from django.db import migrations
def move_piechange_data(apps, schema_editor):
    PiecEchange = apps.get_model("PB_Entreprise", "PiecEchange")
    LignePiecEchange = apps.get_model("PB_Entreprise", "LignePiecEchange")

    for pie in PiecEchange.objects.all():
        LignePiecEchange.objects.create(
            piecec=pie,
            libelle=pie.libelle,
            lieu=pie.lieu,
            montant=pie.montant,
            quantite=1
        )

class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0009_lignepiecechange'),
    ]

    operations = [
        migrations.RunPython(move_piechange_data),
    ]
