# Generated by Django 5.0.2 on 2025-09-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0010_auto_20250911_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecechange',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='piecechange',
            name='lieu',
        ),
    ]
