# Generated by Django 5.0.2 on 2025-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0011_remove_piecechange_libelle_remove_piecechange_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='categovehi',
            name='perte_par_30min',
            field=models.IntegerField(default=0),
        ),
    ]
