# Generated by Django 5.0.2 on 2025-09-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0012_categovehi_perte_par_30min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetage',
            name='nombre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encaissement',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalencaissement',
            name='date_saisie',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
