# Generated by Django 5.0.2 on 2025-09-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0013_alter_billetage_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decaissement',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicaldecaissement',
            name='date_saisie',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
