# Generated by Django 5.0.2 on 2026-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0015_historicalassurance_historicalpatente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicule',
            name='car_statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalvehicule',
            name='motif_sorti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='car_statut',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='motif_sorti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
