# Generated by Django 5.0.2 on 2026-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0016_historicalvehicule_car_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerant',
            name='gerant_voiture',
        ),
        migrations.AddField(
            model_name='gerant',
            name='gerant_voiture',
            field=models.ManyToManyField(blank=True, related_name='gerants', to='PB_Entreprise.categovehi'),
        ),
    ]
