# Generated by Django 6.0.3 on 2026-06-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Entreprise', '0019_userprofile_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_email',
            field=models.BooleanField(default=True, verbose_name='Notifications par e-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_site',
            field=models.BooleanField(default=True, verbose_name='Notifications sur le site'),
        ),
    ]
