# Generated by Django 6.0.3 on 2026-04-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0004_categorieonglet_lien_charfield_and_seed_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image_fond',
        ),
        migrations.AlterField(
            model_name='annonceevenement',
            name='lien',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.CharField(blank=True, help_text='Texte ou nom du logo affiché dans le footer', max_length=200),
        ),
        migrations.AlterField(
            model_name='nosservice',
            name='lien_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partenspons',
            name='lien',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='lien',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_appstore',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_googleplay',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_telechargement_app',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='souscategorieonglet',
            name='lien',
            field=models.CharField(blank=True, help_text='Chemin interne (ex: /) ou URL complète', max_length=500, null=True, verbose_name='Lien du contenu'),
        ),
    ]
