# Generated by Django 6.0.3 on 2026-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0005_remove_article_auteur_remove_footer_image_fond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonceevenement',
            name='lien',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='partenspons',
            name='lien',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='lien',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_appstore',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_googleplay',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='lien_telechargement_app',
            field=models.URLField(blank=True, null=True),
        ),
    ]
