# Generated by Django 6.0.3 on 2026-04-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0007_categorieonglet_accueil_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageaccueil',
            options={'ordering': ['ordre'], 'verbose_name': "Bloc page d'accueil", 'verbose_name_plural': "Page d'accueil"},
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='valeur',
        ),
        migrations.RemoveField(
            model_name='pageaccueil',
            name='background',
        ),
        migrations.RemoveField(
            model_name='pageaccueil',
            name='couleur_fond',
        ),
        migrations.RemoveField(
            model_name='pageaccueil',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='pageaccueil',
            name='taille_texte',
        ),
        migrations.AddField(
            model_name='compteur',
            name='nombre_chauffeur',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de chauffeurs'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='nombre_piece',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de pièces'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='nombre_satisfaction',
            field=models.PositiveIntegerField(default=0, verbose_name='Taux de satisfaction (%)'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='titre',
            field=models.CharField(blank=True, max_length=250, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accueil/'),
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='sous_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='pageaccueil',
            name='titre',
            field=models.CharField(default='', max_length=250, verbose_name='Titre'),
        ),
        migrations.CreateModel(
            name='PilierEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('pilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piliers', to='PBFinance.pageaccueil')),
            ],
            options={
                'verbose_name': "Pilier d'entreprise",
                'verbose_name_plural': "Piliers d'entreprise",
            },
        ),
    ]
