# Generated by Django 6.0.3 on 2026-04-21 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0008_alter_pageaccueil_options_remove_compteur_icone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liencategoriefooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lien categorie footer',
                'verbose_name_plural': 'Liens categorie footer',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterModelOptions(
            name='lienfooter',
            options={'ordering': ['categorie', 'ordre'], 'verbose_name': 'Lien footer', 'verbose_name_plural': 'Liens footer'},
        ),
        migrations.RemoveField(
            model_name='lienfooter',
            name='colonne',
        ),
        migrations.AddField(
            model_name='lienfooter',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liens_categorie_footer', to='PBFinance.liencategoriefooter'),
            preserve_default=False,
        ),
    ]
