# Generated by Django 5.0.2 on 2026-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0009_liencategoriefooter_alter_lienfooter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecedetachee',
            name='badge',
        ),
        migrations.AlterField(
            model_name='applicationcarte',
            name='bouton_lien',
            field=models.CharField(default='#', help_text="Nom d'URL Django (ex: contact, a_propos), chemin (/contact/), URL absolue (https://...) ou ancre (#section).", max_length=500),
        ),
        migrations.AlterField(
            model_name='categorieservice',
            name='bouton_lien',
            field=models.CharField(default='#', help_text="Nom d'URL Django (ex: contact, a_propos), chemin (/contact/), URL absolue (https://...) ou ancre (#section).", max_length=500),
        ),
        migrations.AlterField(
            model_name='promosection',
            name='bouton_lien',
            field=models.CharField(default='#', help_text="Nom d'URL Django (ex: contact, a_propos), chemin (/contact/), URL absolue (https://...) ou ancre (#section).", max_length=500),
        ),
        migrations.AlterField(
            model_name='vehiculelocation',
            name='bouton_lien',
            field=models.CharField(default='#', help_text="Nom d'URL Django (ex: contact, a_propos), chemin (/contact/), URL absolue (https://...) ou ancre (#section).", max_length=500),
        ),
    ]
