# Generated by Django 5.0.2 on 2026-04-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0010_remove_piecedetachee_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemoignagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(blank=True, help_text='Ex: Confort & Disponibilité', max_length=150)),
                ('titre', models.CharField(help_text='Titre principal (peut contenir <br>)', max_length=200)),
                ('description', models.TextField()),
                ('bouton_texte', models.CharField(default='Découvrir', max_length=60)),
                ('bouton_lien', models.CharField(default='#', help_text="URL ou nom d'URL Django", max_length=500)),
                ('bouton_icone', models.CharField(blank=True, default='fa-regular fa-arrow-right', max_length=80)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Slide d'accueil (Hero)",
                'verbose_name_plural': "Slides d'accueil (Hero)",
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='temoignage',
            name='temoignage_page',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='temoignages', to='PBFinance.temoignagepage'),
            preserve_default=False,
        ),
    ]
