# Generated by Django 5.0.2 on 2026-04-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0011_temoignagepage_temoignage_temoignage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseausocial',
            name='image',
        ),
    ]
