# Generated by Django 5.0.2 on 2026-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0012_remove_reseausocial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseausocial',
            name='counter',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total de clics sur l'icône de ce réseau social", verbose_name='Nombre de clics'),
        ),
        migrations.AddField(
            model_name='reseausocial',
            name='date_dernier_clic',
            field=models.DateTimeField(blank=True, help_text="Date/heure du dernier clic enregistré sur l'icône", null=True, verbose_name='Date du dernier clic'),
        ),
    ]
