# Generated by Django 5.0.2 on 2026-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0013_reseausocial_counter_reseausocial_date_dernier_clic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='texte',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='appli_web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_texte',
            field=models.CharField(blank=True, default='Tous droits réservés.', max_length=300),
        ),
    ]
