# Generated by Django 5.0.2 on 2026-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0014_remove_footer_texte_siteconfig_appli_web_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
