# Generated by Django 5.0.2 on 2026-04-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0015_footer_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lien_googleplay', models.URLField(blank=True, null=True)),
                ('lien_appstore', models.URLField(blank=True, null=True)),
                ('lien_web', models.URLField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lien application',
                'verbose_name_plural': 'Liens applications',
            },
        ),
        migrations.DeleteModel(
            name='PageSEO',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='telephone_1',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='adresse_complete',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='appli_web_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='couleur_primaire',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='couleur_secondaire',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='lien_appstore',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='lien_googleplay',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='lien_telechargement_app',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='logo_footer',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telephone_2',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telephone_3',
        ),
    ]
