# Generated by Django 5.0.2 on 2026-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0017_langue'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
