# Generated by Django 5.0.2 on 2026-04-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0018_footer_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=250)),
                ('page', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de procédure',
                'verbose_name_plural': 'Catégories de procédures',
                'ordering': ['ordre', 'page'],
            },
        ),
        migrations.CreateModel(
            name='CatacteristiqueProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(blank=True, help_text='Classe Font Awesome (ex: fa-solid fa-location-dot)', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='procedures/')),
                ('texte', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='PBFinance.categoripage')),
            ],
            options={
                'verbose_name': 'Caractéristique de procédure',
                'verbose_name_plural': 'Caractéristiques de procédures',
                'ordering': ['page', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=250)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='PBFinance.categoripage')),
            ],
            options={
                'verbose_name': 'Page de question',
                'verbose_name_plural': 'Pages de questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('reponse', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='PBFinance.questionpage')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('libelle', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='PBFinance.categoripage')),
            ],
            options={
                'verbose_name': 'Statistique de procédure',
                'verbose_name_plural': 'Statistiques de procédures',
                'ordering': ['ordre'],
            },
        ),
    ]
