# Generated by Django 5.0.2 on 2026-04-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0019_categoripage_catacteristiqueprocedure_questionpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiqueprocedure',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
