# Generated by Django 6.0.3 on 2026-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0020_alter_statistiqueprocedure_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Nom interne du QR code (ex: 'Lien Google Play')", max_length=150)),
                ('lien', models.CharField(help_text='URL ou texte à encoder dans le QR code', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Logo optionnel inséré au centre du QR code', null=True, upload_to='qrcodes/logos/')),
                ('qrcode_image', models.ImageField(blank=True, editable=False, help_text='QR code généré automatiquement', null=True, upload_to='qrcodes/generes/')),
                ('couleur', models.CharField(default='#000000', help_text='Couleur du QR code (hex, ex: #000000)', max_length=20)),
                ('couleur_fond', models.CharField(default='#FFFFFF', help_text='Couleur du fond (hex, ex: #FFFFFF)', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
