# Generated by Django 6.0.3 on 2026-04-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0021_monqrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monqrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='monqrcode',
            name='description',
            field=models.TextField(blank=True, help_text='Description ou note interne (optionnel)', null=True),
        ),
    ]
