# Generated by Django 5.0.2 on 2026-04-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0023_gestionsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiqueprocedure',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe Font Awesome (ex: fa-solid fa-location-dot)', max_length=100, null=True),
        ),
    ]
