# Generated by Django 6.0.3 on 2026-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0024_statistiqueprocedure_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIntroPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('chauffeurs', 'Chauffeurs'), ('livreur', 'Livreur'), ('clients', 'Clients')], db_index=True, max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('sous_titre', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=250)),
                ('texte', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages_intro/')),
                ('position_image', models.CharField(choices=[('gauche', 'Image à gauche, texte à droite'), ('droite', 'Image à droite, texte à gauche')], default='droite', help_text="Côté de l'image (le texte se place de l'autre côté).", max_length=10)),
                ('classes_section', models.CharField(blank=True, help_text='Classes CSS supplémentaires sur la balise <section> (ex. : pb-120).', max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Section d'intro (page contenu)",
                'verbose_name_plural': "Sections d'intro (pages contenu)",
                'ordering': ['page', 'ordre', 'pk'],
            },
        ),
    ]
