# Generated by Django 5.0.2 on 2026-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0025_section_intro_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Ex: 5.3617', max_digits=9),
        ),
        migrations.AlterField(
            model_name='agence',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Ex: -3.8866', max_digits=9),
        ),
    ]
