# Generated by Django 5.0.2 on 2026-04-30 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0026_alter_agence_latitude_alter_agence_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(blank=True, max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/')),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie application',
                'verbose_name_plural': 'Catégories applications',
                'ordering': ['ordre'],
            },
        ),
        migrations.RemoveField(
            model_name='applicationcarte',
            name='image',
        ),
        migrations.AddField(
            model_name='applicationcarte',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationcarte',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicationcarte',
            name='bouton_lien',
            field=models.URLField(blank=True, help_text="Nom d'URL Django (ex: contact, a_propos), chemin (/contact/), URL absolue (https://...) ou ancre (#section).", null=True),
        ),
        migrations.AddField(
            model_name='applicationcarte',
            name='categorie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='PBFinance.categorieapplication'),
            preserve_default=False,
        ),
    ]
