# Generated by Django 6.0.3 on 2026-04-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0027_categorieapplication_remove_applicationcarte_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieGestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique unique (ex: home, chauffeurs, livreur, clients)', unique=True)),
                ('libelle', models.CharField(help_text='Nom affiché en administration', max_length=120)),
                ('template_path', models.CharField(blank=True, help_text='Chemin template optionnel (ex: pb_site/index-3.html)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie gestion section',
                'verbose_name_plural': 'Catégories gestion sections',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='gestionsection',
            options={'ordering': ['categorie__ordre', 'titre_section'], 'verbose_name': 'Gestion de section (accueil)', 'verbose_name_plural': 'Gestion des sections (accueil)'},
        ),
        migrations.AlterField(
            model_name='gestionsection',
            name='titre_section',
            field=models.CharField(help_text='Clé technique de section (ex: promo, nos_services, hero, faq, etc.)', max_length=80, verbose_name='Section concernée'),
        ),
        migrations.AddField(
            model_name='gestionsection',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='PBFinance.categoriegestionsection', verbose_name='Catégorie de page'),
        ),
        migrations.AlterUniqueTogether(
            name='gestionsection',
            unique_together={('categorie', 'titre_section')},
        ),
    ]
