# Generated by Django 5.0.2 on 2026-04-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0028_categoriegestionsection_alter_gestionsection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriegestionsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoriegestionsection',
            name='template_path',
        ),
    ]
