# Generated by Django 5.0.2 on 2026-05-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0029_remove_categoriegestionsection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catacteristiqueprocedure',
            name='image',
        ),
    ]
