# Generated by Django 5.0.2 on 2026-05-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0030_remove_catacteristiqueprocedure_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['ordre', '-date_publication'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles (Blog)'},
        ),
        migrations.RemoveField(
            model_name='catacteristiqueprocedure',
            name='icone',
        ),
        migrations.AddField(
            model_name='article',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
