# Generated by Django 5.0.2 on 2026-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0031_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catacteristiqueprocedure',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe Font Awesome (ex: fa-solid fa-location-dot)', max_length=100, null=True),
        ),
    ]
