# Generated by Django 5.0.2 on 2026-05-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0032_catacteristiqueprocedure_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catacteristiqueprocedure',
            name='icone',
        ),
    ]
