# Generated by Django 5.0.2 on 2026-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0033_remove_catacteristiqueprocedure_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionintropage',
            name='page',
            field=models.CharField(choices=[('chauffeurs', 'Chauffeurs'), ('livreur', 'Livreur'), ('clients', 'Clients'), ('assistance', 'Assistance')], db_index=True, max_length=20),
        ),
    ]
