# Generated by Django 5.0.2 on 2026-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0034_alter_sectionintropage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecedetachee',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='piecedetachee',
            name='unite_prix',
            field=models.CharField(default='Par Pièce', help_text='Ex: Par Pièce, Par Kg, Par Litre, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='sectionintropage',
            name='page',
            field=models.CharField(choices=[('chauffeurs', 'Chauffeurs'), ('livreur', 'Livreur'), ('clients', 'Clients'), ('assistance', 'Assistance'), ('services', 'Services')], db_index=True, max_length=20),
        ),
    ]
