# Generated by Django 5.0.2 on 2026-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0035_piecedetachee_prix_piecedetachee_unite_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainsChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gains chauffeur',
                'verbose_name_plural': 'Gains chauffeurs',
                'ordering': ['ordre'],
            },
        ),
    ]
