# Generated by Django 6.0.3 on 2026-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0036_gainschauffeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gainschauffeur',
            options={'ordering': ['ordre', 'pk'], 'verbose_name': 'Gains chauffeur', 'verbose_name_plural': 'Gains chauffeurs'},
        ),
        migrations.AlterField(
            model_name='gainschauffeur',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='FCFA : si ordre = 0, taux horaire de référence (Abidjan) ; sinon objectif hebdomadaire.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gainschauffeur',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text='0 = taux horaire (une ligne). ≥1 = montants des boutons « revenu souhaité » (semaine), triés.'),
        ),
    ]
