# Generated by Django 6.0.3 on 2026-05-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0037_gainschauffeur_model_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='gainschauffeur',
            name='montant_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Uniquement pour ordre = 0 : taux horaire « rond » affiché et utilisé pour le simulateur (ex. 3214). Vide = utiliser « montant » seul.', max_digits=10, null=True, verbose_name='Montant de base'),
        ),
        migrations.AlterField(
            model_name='gainschauffeur',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='FCFA : si ordre = 0, taux horaire (précis) ou complément si « montant de base » est rempli ; sinon objectif hebdomadaire.', max_digits=10),
        ),
    ]
