# Generated by Django 5.0.2 on 2026-05-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0038_gainschauffeur_montant_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionintropage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_intro', to='PBFinance.categoripage'),
        ),
    ]
