# Generated by Django 5.0.2 on 2026-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0039_alter_sectionintropage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/'),
        ),
    ]
