# Generated by Django 5.0.2 on 2026-05-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0040_lienapplication_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lienapplication',
            old_name='lien_appstore',
            new_name='lien_store',
        ),
        migrations.RemoveField(
            model_name='lienapplication',
            name='lien_googleplay',
        ),
        migrations.RemoveField(
            model_name='lienapplication',
            name='lien_web',
        ),
    ]
